// Sirven para explicar que pasa en la aplicación
export const AGREGAR_SEGUIMIENTO = "AGREGAR_SEGUIMIENTO";
export const AGREGAR_SEGUIMIENTO_EXITO = "AGREGAR SEGUIMIENTO_EXITO";
export const AGREGAR_SEGUIMIENTO_ERROR = "AGREGAR SEGUIMIENTO_ERROR";

export const LISTAR_SEGUIMIENTOS = "LISTAR_SEGUIMIENTO";
export const LISTAR_SEGUIMIENTOS_EXITO = "LISTAR_SEGUIMIENTOS_EXITO";
export const LISTAR_SEGUIMIENTOS_ERROR = "LISTAR_SEGUIMIENTOS_ERROR";

export const LISTAR_ENTREVISTAS = "LISTAR_ENTREVISTAS";
export const LISTAR_ENTREVISTAS_EXITO = "LISTAR_ENTREVISTAS_EXITO";
export const LISTAR_ENTREVISTAS_ERROR = "LISTAR_ENTREVISTAS_ERROR";

export const AGREGAR_OBSERVACION = "AGREGAR_OBSERVACIONS";
export const AGREGAR_OBSERVACION_EXITO = "AGREGAR OBSERVACION_EXITO";
export const AGREGAR_OBSERVACION_ERROR = "AGREGAR OBSERVACION_ERROR";

export const AGREGAR_ACCION = "AGREGAR_ACCIONS";
export const AGREGAR_ACCION_EXITO = "AGREGAR ACCION_EXITO";
export const AGREGAR_ACCION_ERROR = "AGREGAR ACCION_ERROR";
