// Sirven para explicar que pasa en la aplicación
export const CREAR_SEGUIMIENTO = "CREAR_SEGUIMIENTO";
export const CREAR_SEGUIMIENTO_EXITO = "CREAR SEGUIMIENTO_EXITO";
export const CREAR_SEGUIMIENTO_ERROR = "CREAR SEGUIMIENTO_ERROR";

export const LISTAR_SEGUIMIENTOS = "LISTAR_SEGUIMIENTO";
export const LISTAR_SEGUIMIENTOS_EXITO = "LISTAR_SEGUIMIENTOS_EXITO";
export const LISTAR_SEGUIMIENTOS_ERROR = "LISTAR_SEGUIMIENTOS_ERROR";

export const LISTAR_ENTREVISTAS = "LISTAR_ENTREVISTAS";
export const LISTAR_ENTREVISTAS_EXITO = "LISTAR_ENTREVISTAS_EXITO";
export const LISTAR_ENTREVISTAS_ERROR = "LISTAR_ENTREVISTAS_ERROR";

export const CREAR_OBSERVACION = "CREAR_OBSERVACIONS";
export const CREAR_OBSERVACION_EXITO = "CREAR OBSERVACION_EXITO";
export const CREAR_OBSERVACION_ERROR = "CREAR OBSERVACION_ERROR";

export const CREAR_ACCION = "CREAR_ACCION";
export const CREAR_ACCION_EXITO = "CREAR ACCION_EXITO";
export const CREAR_ACCION_ERROR = "CREAR ACCION_ERROR";
